/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupConfirmRouteImport } from './routes/signup-confirm'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FirstLoginRouteImport } from './routes/first-login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreateCragRouteImport } from './routes/create-crag'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CragsIndexRouteImport } from './routes/crags/index'
import { Route as ResetPasswordConfirmRouteImport } from './routes/reset-password/confirm'
import { Route as ApiCallbackRouteImport } from './routes/api/callback'
import { Route as CragsCragSlugIndexRouteImport } from './routes/crags/$cragSlug/index'
import { Route as CragsCragSlugCreateAreaRouteImport } from './routes/crags/$cragSlug/create-area'
import { Route as CragsCragSlugCreateTopoAreaSlugRouteImport } from './routes/crags/$cragSlug/create-topo.$areaSlug'
import { Route as CragsCragSlugAreasAreaSlugIndexRouteImport } from './routes/crags/$cragSlug/areas/$areaSlug/index'
import { Route as CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRouteImport } from './routes/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route'
import { Route as CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRouteImport } from './routes/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/index'
import { Route as CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRouteImport } from './routes/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit'

const SignupConfirmRoute = SignupConfirmRouteImport.update({
  id: '/signup-confirm',
  path: '/signup-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstLoginRoute = FirstLoginRouteImport.update({
  id: '/first-login',
  path: '/first-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCragRoute = CreateCragRouteImport.update({
  id: '/create-crag',
  path: '/create-crag',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CragsIndexRoute = CragsIndexRouteImport.update({
  id: '/crags/',
  path: '/crags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordConfirmRoute = ResetPasswordConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => ResetPasswordRoute,
} as any)
const ApiCallbackRoute = ApiCallbackRouteImport.update({
  id: '/api/callback',
  path: '/api/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CragsCragSlugIndexRoute = CragsCragSlugIndexRouteImport.update({
  id: '/crags/$cragSlug/',
  path: '/crags/$cragSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CragsCragSlugCreateAreaRoute = CragsCragSlugCreateAreaRouteImport.update({
  id: '/crags/$cragSlug/create-area',
  path: '/crags/$cragSlug/create-area',
  getParentRoute: () => rootRouteImport,
} as any)
const CragsCragSlugCreateTopoAreaSlugRoute =
  CragsCragSlugCreateTopoAreaSlugRouteImport.update({
    id: '/crags/$cragSlug/create-topo/$areaSlug',
    path: '/crags/$cragSlug/create-topo/$areaSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CragsCragSlugAreasAreaSlugIndexRoute =
  CragsCragSlugAreasAreaSlugIndexRouteImport.update({
    id: '/crags/$cragSlug/areas/$areaSlug/',
    path: '/crags/$cragSlug/areas/$areaSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRoute =
  CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRouteImport.update({
    id: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route',
    path: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route',
    getParentRoute: () => rootRouteImport,
  } as any)
const CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRoute =
  CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRouteImport.update(
    {
      id: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/',
      path: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRoute =
  CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRouteImport.update({
    id: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit',
    path: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-crag': typeof CreateCragRoute
  '/explore': typeof ExploreRoute
  '/first-login': typeof FirstLoginRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/signup-confirm': typeof SignupConfirmRoute
  '/api/callback': typeof ApiCallbackRoute
  '/reset-password/confirm': typeof ResetPasswordConfirmRoute
  '/crags/': typeof CragsIndexRoute
  '/crags/$cragSlug/create-area': typeof CragsCragSlugCreateAreaRoute
  '/crags/$cragSlug/': typeof CragsCragSlugIndexRoute
  '/crags/$cragSlug/create-topo/$areaSlug': typeof CragsCragSlugCreateTopoAreaSlugRoute
  '/crags/$cragSlug/areas/$areaSlug/': typeof CragsCragSlugAreasAreaSlugIndexRoute
  '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route': typeof CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRoute
  '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit': typeof CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRoute
  '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/': typeof CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-crag': typeof CreateCragRoute
  '/explore': typeof ExploreRoute
  '/first-login': typeof FirstLoginRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/signup-confirm': typeof SignupConfirmRoute
  '/api/callback': typeof ApiCallbackRoute
  '/reset-password/confirm': typeof ResetPasswordConfirmRoute
  '/crags': typeof CragsIndexRoute
  '/crags/$cragSlug/create-area': typeof CragsCragSlugCreateAreaRoute
  '/crags/$cragSlug': typeof CragsCragSlugIndexRoute
  '/crags/$cragSlug/create-topo/$areaSlug': typeof CragsCragSlugCreateTopoAreaSlugRoute
  '/crags/$cragSlug/areas/$areaSlug': typeof CragsCragSlugAreasAreaSlugIndexRoute
  '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route': typeof CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRoute
  '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit': typeof CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRoute
  '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug': typeof CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-crag': typeof CreateCragRoute
  '/explore': typeof ExploreRoute
  '/first-login': typeof FirstLoginRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/signup-confirm': typeof SignupConfirmRoute
  '/api/callback': typeof ApiCallbackRoute
  '/reset-password/confirm': typeof ResetPasswordConfirmRoute
  '/crags/': typeof CragsIndexRoute
  '/crags/$cragSlug/create-area': typeof CragsCragSlugCreateAreaRoute
  '/crags/$cragSlug/': typeof CragsCragSlugIndexRoute
  '/crags/$cragSlug/create-topo/$areaSlug': typeof CragsCragSlugCreateTopoAreaSlugRoute
  '/crags/$cragSlug/areas/$areaSlug/': typeof CragsCragSlugAreasAreaSlugIndexRoute
  '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route': typeof CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRoute
  '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit': typeof CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRoute
  '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/': typeof CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-crag'
    | '/explore'
    | '/first-login'
    | '/home'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/signup-confirm'
    | '/api/callback'
    | '/reset-password/confirm'
    | '/crags/'
    | '/crags/$cragSlug/create-area'
    | '/crags/$cragSlug/'
    | '/crags/$cragSlug/create-topo/$areaSlug'
    | '/crags/$cragSlug/areas/$areaSlug/'
    | '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route'
    | '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit'
    | '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-crag'
    | '/explore'
    | '/first-login'
    | '/home'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/signup-confirm'
    | '/api/callback'
    | '/reset-password/confirm'
    | '/crags'
    | '/crags/$cragSlug/create-area'
    | '/crags/$cragSlug'
    | '/crags/$cragSlug/create-topo/$areaSlug'
    | '/crags/$cragSlug/areas/$areaSlug'
    | '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route'
    | '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit'
    | '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug'
  id:
    | '__root__'
    | '/'
    | '/create-crag'
    | '/explore'
    | '/first-login'
    | '/home'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/signup-confirm'
    | '/api/callback'
    | '/reset-password/confirm'
    | '/crags/'
    | '/crags/$cragSlug/create-area'
    | '/crags/$cragSlug/'
    | '/crags/$cragSlug/create-topo/$areaSlug'
    | '/crags/$cragSlug/areas/$areaSlug/'
    | '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route'
    | '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit'
    | '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateCragRoute: typeof CreateCragRoute
  ExploreRoute: typeof ExploreRoute
  FirstLoginRoute: typeof FirstLoginRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRouteWithChildren
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SignupConfirmRoute: typeof SignupConfirmRoute
  ApiCallbackRoute: typeof ApiCallbackRoute
  CragsIndexRoute: typeof CragsIndexRoute
  CragsCragSlugCreateAreaRoute: typeof CragsCragSlugCreateAreaRoute
  CragsCragSlugIndexRoute: typeof CragsCragSlugIndexRoute
  CragsCragSlugCreateTopoAreaSlugRoute: typeof CragsCragSlugCreateTopoAreaSlugRoute
  CragsCragSlugAreasAreaSlugIndexRoute: typeof CragsCragSlugAreasAreaSlugIndexRoute
  CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRoute: typeof CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRoute
  CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRoute: typeof CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRoute
  CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRoute: typeof CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup-confirm': {
      id: '/signup-confirm'
      path: '/signup-confirm'
      fullPath: '/signup-confirm'
      preLoaderRoute: typeof SignupConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-login': {
      id: '/first-login'
      path: '/first-login'
      fullPath: '/first-login'
      preLoaderRoute: typeof FirstLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-crag': {
      id: '/create-crag'
      path: '/create-crag'
      fullPath: '/create-crag'
      preLoaderRoute: typeof CreateCragRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crags/': {
      id: '/crags/'
      path: '/crags'
      fullPath: '/crags/'
      preLoaderRoute: typeof CragsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/confirm': {
      id: '/reset-password/confirm'
      path: '/confirm'
      fullPath: '/reset-password/confirm'
      preLoaderRoute: typeof ResetPasswordConfirmRouteImport
      parentRoute: typeof ResetPasswordRoute
    }
    '/api/callback': {
      id: '/api/callback'
      path: '/api/callback'
      fullPath: '/api/callback'
      preLoaderRoute: typeof ApiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crags/$cragSlug/': {
      id: '/crags/$cragSlug/'
      path: '/crags/$cragSlug'
      fullPath: '/crags/$cragSlug/'
      preLoaderRoute: typeof CragsCragSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crags/$cragSlug/create-area': {
      id: '/crags/$cragSlug/create-area'
      path: '/crags/$cragSlug/create-area'
      fullPath: '/crags/$cragSlug/create-area'
      preLoaderRoute: typeof CragsCragSlugCreateAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crags/$cragSlug/create-topo/$areaSlug': {
      id: '/crags/$cragSlug/create-topo/$areaSlug'
      path: '/crags/$cragSlug/create-topo/$areaSlug'
      fullPath: '/crags/$cragSlug/create-topo/$areaSlug'
      preLoaderRoute: typeof CragsCragSlugCreateTopoAreaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crags/$cragSlug/areas/$areaSlug/': {
      id: '/crags/$cragSlug/areas/$areaSlug/'
      path: '/crags/$cragSlug/areas/$areaSlug'
      fullPath: '/crags/$cragSlug/areas/$areaSlug/'
      preLoaderRoute: typeof CragsCragSlugAreasAreaSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route': {
      id: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route'
      path: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route'
      fullPath: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/create-route'
      preLoaderRoute: typeof CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/': {
      id: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/'
      path: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug'
      fullPath: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/'
      preLoaderRoute: typeof CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit': {
      id: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit'
      path: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit'
      fullPath: '/crags/$cragSlug/areas/$areaSlug/topos/$topoSlug/routes/$routeSlug/edit'
      preLoaderRoute: typeof CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResetPasswordRouteChildren {
  ResetPasswordConfirmRoute: typeof ResetPasswordConfirmRoute
}

const ResetPasswordRouteChildren: ResetPasswordRouteChildren = {
  ResetPasswordConfirmRoute: ResetPasswordConfirmRoute,
}

const ResetPasswordRouteWithChildren = ResetPasswordRoute._addFileChildren(
  ResetPasswordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateCragRoute: CreateCragRoute,
  ExploreRoute: ExploreRoute,
  FirstLoginRoute: FirstLoginRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRouteWithChildren,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SignupConfirmRoute: SignupConfirmRoute,
  ApiCallbackRoute: ApiCallbackRoute,
  CragsIndexRoute: CragsIndexRoute,
  CragsCragSlugCreateAreaRoute: CragsCragSlugCreateAreaRoute,
  CragsCragSlugIndexRoute: CragsCragSlugIndexRoute,
  CragsCragSlugCreateTopoAreaSlugRoute: CragsCragSlugCreateTopoAreaSlugRoute,
  CragsCragSlugAreasAreaSlugIndexRoute: CragsCragSlugAreasAreaSlugIndexRoute,
  CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRoute:
    CragsCragSlugAreasAreaSlugToposTopoSlugCreateRouteRoute,
  CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRoute:
    CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugEditRoute,
  CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRoute:
    CragsCragSlugAreasAreaSlugToposTopoSlugRoutesRouteSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
