export default {
  gradingSystems: [
    {
      gradingSystemTitle: "Font",
      grades: [
        "3",
        "4",
        "4+",
        "5",
        "5+",
        "6A",
        "6A+",
        "6B",
        "6B+",
        "6C",
        "6C+",
        "7A",
        "7A+",
        "7B",
        "7B+",
        "7C",
        "7C+",
        "8A",
        "8A+",
        "8B",
        "8B+",
        "8C",
        "8C+",
        "9A",
        "9A+",
        "9B",
        "9B+",
        "9C",
        "9C+",
      ]
    },
  ],
  cragTags: [
    "Quick Drying",
    "Slow Drying",
    "Quick Walk-in",
    "Long Walk-in",
    "Esoteric",
    "Family Friendly",
    "Good Landings"
  ],
  areaTags: [],
  routeTags: [],
  rockTypes: [
    "Gritstone",
    "Limestone",
  ],
}
