export default {
  gradingSystems: [
    {
      title: "Font",
      grades: [
        "3",
        "4",
        "4+",
        "5",
        "5+",
        "6A",
        "6A+",
        "6B",
        "6B+",
        "6C",
        "6C+",
        "7A",
        "7A+",
        "7B",
        "7B+",
        "7C",
        "7C+",
        "8A",
        "8A+",
        "8B",
        "8B+",
        "8C",
        "8C+",
        "9A",
        "9A+",
        "9B",
        "9B+",
        "9C",
        "9C+",
      ]
    },
    {
      title: "V Grade",
      grades: [
        "V0",
        "V1",
        "V2",
        "V3",
        "V4",
        "V5",
        "V6",
        "V7",
        "V8",
        "V9",
        "V10",
        "V11",
        "V12",
        "V13",
        "V14",
        "V15",
        "V16",
        "V17",
      ]
    }
  ],
  cragTags: [
    "Quick Drying",
    "Slow Drying",
    "Quick Walk-in",
    "Long Walk-in",
    "Esoteric",
    "Family Friendly",
    "Good Landings",
    "Highballs",
    "Lowballs",
    "Public Transport"
  ],
  areaTags: [
    "Quick Drying",
    "Slow Drying",
    "Easy Access",
    "Hard to Find",
    "Highballs",
    "Lowballs",
    "Needs a Brush",
    "Bad Landings",
    "Good Landings"
  ],
  routeTags: [
    "Crimps",
    "Slopers",
    "Pockets",
    "Jugs",
    "Gaston",
    "Undercuts",
    "Highball",
    "Lowball",
    "Slab",
    "Overhanging",
    "Vert"
  ],
  routeTypes: ["Sport Climb", "Trad", "Boulder"],
  rockTypes: [
    "Gritstone",
    "Limestone",
  ],
}
