org: jjohnson1994
app: climbing-topos
service: climbing-topos

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
custom:
  aliasDNSName: 's3-website-eu-west-1.amazonaws.com'
  aliasHostedZoneId: 'Z0796811MPC87A5CPC2B'
  siteName: 'climbingtopos.com'
  tableName: 'climbing_topos'
  imageBucketName: 'climbing-topos-images'
  serverless-offline:
    httpPort: 3001
  webpack:
    webpackConfig: 'webpack.config.js'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds-data:ExecuteStatement
      Resource: '*' #TODO get resource arn from Terraform
    - Effect: Allow
      Action:
        - secretsmanager:GetResourcePolicy
        - secretsmanager:GetSecretValue
        - secretsmanager:DescribeSecret
        - secretsmanager:ListSecretVersionIds
      Resource: '*' #TODO get resource arn from Terraform
    - Effect: Allow
      Action:
        - s3:putObject
      Resource: '*' #TODO get resource arn from Terraform

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    cors: true
