org: jjohnson1994
app: climbing-topos
service: climbing-topos

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
custom:
  aliasDNSName: 's3-website-eu-west-1.amazonaws.com'
  aliasHostedZoneId: 'Z0796811MPC87A5CPC2B'
  siteName: 'climbingtopos.com'
  tableName: 'climbing_topos'
  imageBucketName: 'climbing-topos-images'
  serverless-offline:
    httpPort: 3001
  webpack:
    webpackConfig: 'webpack.config.js'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  cragsGet:
    handler: index.handler
    events:
      - http: 'GET /crags/{proxy+}'
  cragsPost:
    handler: index.handler
    events:
      - http: 'POST /crags/{proxy+}'
